namespace HOSPITAL_MANAGEMENT_SOURCE.GUI
{
    partial class FormMainRole
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormMainRole));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonRoleDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.bunifuButtonRoleEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButtonRoleAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuDataGridViewRoleDetail = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuDataGridViewRole = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifubuttonRoleDeleteSearch = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBoxRoleSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewRoleDetail)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewRole)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 55;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = null;
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = null;
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = null;
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = null;
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(221)))), ((int)(((byte)(85)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 50;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(153)))), ((int)(((byte)(139)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(153)))), ((int)(((byte)(139)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1095, 717);
            this.bunifuGradientPanel1.TabIndex = 6;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.BorderRadius = 30;
            this.bunifuShadowPanel1.BorderThickness = 0;
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox3);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonRoleDelete);
            this.bunifuShadowPanel1.Controls.Add(this.pictureBox2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonRoleEdit);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButtonRoleAdd);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuButton10);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDataGridViewRoleDetail);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuDataGridViewRole);
            this.bunifuShadowPanel1.Controls.Add(this.bunifubuttonRoleDeleteSearch);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBoxRoleSearch);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(30, 28);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 0;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(1024, 665);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 5;
            this.bunifuToolTip1.SetToolTip(this.bunifuShadowPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuShadowPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuShadowPanel1, "");
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.pictureBox1.Image = global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_removebg_preview;
            this.pictureBox1.Location = new System.Drawing.Point(680, 606);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(33, 33);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 39;
            this.pictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.pictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pictureBox1, "");
            // 
            // pictureBox3
            // 
            this.pictureBox3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.pictureBox3.Image = global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview;
            this.pictureBox3.Location = new System.Drawing.Point(538, 606);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(36, 33);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 38;
            this.pictureBox3.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.pictureBox3, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pictureBox3, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pictureBox3, "");
            // 
            // bunifuButtonRoleDelete
            // 
            this.bunifuButtonRoleDelete.AllowAnimations = true;
            this.bunifuButtonRoleDelete.AllowMouseEffects = true;
            this.bunifuButtonRoleDelete.AllowToggling = false;
            this.bunifuButtonRoleDelete.AnimationSpeed = 200;
            this.bunifuButtonRoleDelete.AutoGenerateColors = false;
            this.bunifuButtonRoleDelete.AutoRoundBorders = false;
            this.bunifuButtonRoleDelete.AutoSizeLeftIcon = true;
            this.bunifuButtonRoleDelete.AutoSizeRightIcon = true;
            this.bunifuButtonRoleDelete.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonRoleDelete.BackgroundImage")));
            this.bunifuButtonRoleDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonRoleDelete.ButtonText = "      Xóa";
            this.bunifuButtonRoleDelete.ButtonTextMarginLeft = 0;
            this.bunifuButtonRoleDelete.ColorContrastOnClick = 45;
            this.bunifuButtonRoleDelete.ColorContrastOnHover = 45;
            this.bunifuButtonRoleDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonRoleDelete.CustomizableEdges = borderEdges1;
            this.bunifuButtonRoleDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonRoleDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRoleDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRoleDelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRoleDelete.Enabled = false;
            this.bunifuButtonRoleDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonRoleDelete.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonRoleDelete.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonRoleDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonRoleDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRoleDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonRoleDelete.IconMarginLeft = 11;
            this.bunifuButtonRoleDelete.IconPadding = 10;
            this.bunifuButtonRoleDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonRoleDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRoleDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonRoleDelete.IconSize = 25;
            this.bunifuButtonRoleDelete.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleDelete.IdleBorderRadius = 24;
            this.bunifuButtonRoleDelete.IdleBorderThickness = 2;
            this.bunifuButtonRoleDelete.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleDelete.IdleIconLeftImage = null;
            this.bunifuButtonRoleDelete.IdleIconRightImage = null;
            this.bunifuButtonRoleDelete.IndicateFocus = false;
            this.bunifuButtonRoleDelete.Location = new System.Drawing.Point(518, 596);
            this.bunifuButtonRoleDelete.Name = "bunifuButtonRoleDelete";
            this.bunifuButtonRoleDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRoleDelete.OnDisabledState.BorderRadius = 24;
            this.bunifuButtonRoleDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleDelete.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonRoleDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRoleDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRoleDelete.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonRoleDelete.OnDisabledState.IconRightImage = null;
            this.bunifuButtonRoleDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRoleDelete.onHoverState.BorderRadius = 24;
            this.bunifuButtonRoleDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleDelete.onHoverState.BorderThickness = 2;
            this.bunifuButtonRoleDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRoleDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRoleDelete.onHoverState.IconLeftImage = null;
            this.bunifuButtonRoleDelete.onHoverState.IconRightImage = null;
            this.bunifuButtonRoleDelete.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleDelete.OnIdleState.BorderRadius = 24;
            this.bunifuButtonRoleDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonRoleDelete.OnIdleState.BorderThickness = 2;
            this.bunifuButtonRoleDelete.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleDelete.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonRoleDelete.OnIdleState.IconLeftImage = null;
            this.bunifuButtonRoleDelete.OnIdleState.IconRightImage = null;
            this.bunifuButtonRoleDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRoleDelete.OnPressedState.BorderRadius = 24;
            this.bunifuButtonRoleDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleDelete.OnPressedState.BorderThickness = 2;
            this.bunifuButtonRoleDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRoleDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRoleDelete.OnPressedState.IconLeftImage = null;
            this.bunifuButtonRoleDelete.OnPressedState.IconRightImage = null;
            this.bunifuButtonRoleDelete.Size = new System.Drawing.Size(130, 50);
            this.bunifuButtonRoleDelete.TabIndex = 37;
            this.bunifuButtonRoleDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonRoleDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonRoleDelete.TextMarginLeft = 0;
            this.bunifuButtonRoleDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButtonRoleDelete, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButtonRoleDelete, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButtonRoleDelete, "");
            this.bunifuButtonRoleDelete.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonRoleDelete.Click += new System.EventHandler(this.bunifuButtonRoleDelete_Click);
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.pictureBox2.Image = global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.vecteezy_interface_plus_user_business_flat_line_filled_icon_vector_19177343_removebg_preview__1_;
            this.pictureBox2.Location = new System.Drawing.Point(830, 606);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(33, 33);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 36;
            this.pictureBox2.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.pictureBox2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pictureBox2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pictureBox2, "");
            // 
            // bunifuButtonRoleEdit
            // 
            this.bunifuButtonRoleEdit.AllowAnimations = true;
            this.bunifuButtonRoleEdit.AllowMouseEffects = true;
            this.bunifuButtonRoleEdit.AllowToggling = false;
            this.bunifuButtonRoleEdit.AnimationSpeed = 200;
            this.bunifuButtonRoleEdit.AutoGenerateColors = false;
            this.bunifuButtonRoleEdit.AutoRoundBorders = false;
            this.bunifuButtonRoleEdit.AutoSizeLeftIcon = true;
            this.bunifuButtonRoleEdit.AutoSizeRightIcon = true;
            this.bunifuButtonRoleEdit.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonRoleEdit.BackgroundImage")));
            this.bunifuButtonRoleEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonRoleEdit.ButtonText = "         Thay đổi";
            this.bunifuButtonRoleEdit.ButtonTextMarginLeft = 0;
            this.bunifuButtonRoleEdit.ColorContrastOnClick = 45;
            this.bunifuButtonRoleEdit.ColorContrastOnHover = 45;
            this.bunifuButtonRoleEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButtonRoleEdit.CustomizableEdges = borderEdges2;
            this.bunifuButtonRoleEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonRoleEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRoleEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRoleEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRoleEdit.Enabled = false;
            this.bunifuButtonRoleEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonRoleEdit.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonRoleEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonRoleEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonRoleEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRoleEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonRoleEdit.IconMarginLeft = 11;
            this.bunifuButtonRoleEdit.IconPadding = 10;
            this.bunifuButtonRoleEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonRoleEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRoleEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonRoleEdit.IconSize = 25;
            this.bunifuButtonRoleEdit.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleEdit.IdleBorderRadius = 24;
            this.bunifuButtonRoleEdit.IdleBorderThickness = 2;
            this.bunifuButtonRoleEdit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleEdit.IdleIconLeftImage = null;
            this.bunifuButtonRoleEdit.IdleIconRightImage = null;
            this.bunifuButtonRoleEdit.IndicateFocus = false;
            this.bunifuButtonRoleEdit.Location = new System.Drawing.Point(668, 596);
            this.bunifuButtonRoleEdit.Name = "bunifuButtonRoleEdit";
            this.bunifuButtonRoleEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRoleEdit.OnDisabledState.BorderRadius = 24;
            this.bunifuButtonRoleEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleEdit.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonRoleEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRoleEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRoleEdit.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonRoleEdit.OnDisabledState.IconRightImage = null;
            this.bunifuButtonRoleEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRoleEdit.onHoverState.BorderRadius = 24;
            this.bunifuButtonRoleEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleEdit.onHoverState.BorderThickness = 2;
            this.bunifuButtonRoleEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRoleEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRoleEdit.onHoverState.IconLeftImage = null;
            this.bunifuButtonRoleEdit.onHoverState.IconRightImage = null;
            this.bunifuButtonRoleEdit.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleEdit.OnIdleState.BorderRadius = 24;
            this.bunifuButtonRoleEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonRoleEdit.OnIdleState.BorderThickness = 2;
            this.bunifuButtonRoleEdit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleEdit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonRoleEdit.OnIdleState.IconLeftImage = null;
            this.bunifuButtonRoleEdit.OnIdleState.IconRightImage = null;
            this.bunifuButtonRoleEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRoleEdit.OnPressedState.BorderRadius = 24;
            this.bunifuButtonRoleEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleEdit.OnPressedState.BorderThickness = 2;
            this.bunifuButtonRoleEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRoleEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRoleEdit.OnPressedState.IconLeftImage = null;
            this.bunifuButtonRoleEdit.OnPressedState.IconRightImage = null;
            this.bunifuButtonRoleEdit.Size = new System.Drawing.Size(130, 50);
            this.bunifuButtonRoleEdit.TabIndex = 35;
            this.bunifuButtonRoleEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonRoleEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonRoleEdit.TextMarginLeft = 0;
            this.bunifuButtonRoleEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButtonRoleEdit, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButtonRoleEdit, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButtonRoleEdit, "");
            this.bunifuButtonRoleEdit.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonRoleEdit.Click += new System.EventHandler(this.bunifuButtonRoleEdit_Click);
            // 
            // bunifuButtonRoleAdd
            // 
            this.bunifuButtonRoleAdd.AllowAnimations = true;
            this.bunifuButtonRoleAdd.AllowMouseEffects = true;
            this.bunifuButtonRoleAdd.AllowToggling = false;
            this.bunifuButtonRoleAdd.AnimationSpeed = 200;
            this.bunifuButtonRoleAdd.AutoGenerateColors = false;
            this.bunifuButtonRoleAdd.AutoRoundBorders = false;
            this.bunifuButtonRoleAdd.AutoSizeLeftIcon = true;
            this.bunifuButtonRoleAdd.AutoSizeRightIcon = true;
            this.bunifuButtonRoleAdd.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonRoleAdd.BackgroundImage")));
            this.bunifuButtonRoleAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonRoleAdd.ButtonText = "          Thêm mới";
            this.bunifuButtonRoleAdd.ButtonTextMarginLeft = 0;
            this.bunifuButtonRoleAdd.ColorContrastOnClick = 45;
            this.bunifuButtonRoleAdd.ColorContrastOnHover = 45;
            this.bunifuButtonRoleAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButtonRoleAdd.CustomizableEdges = borderEdges3;
            this.bunifuButtonRoleAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonRoleAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRoleAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRoleAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRoleAdd.Enabled = false;
            this.bunifuButtonRoleAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonRoleAdd.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonRoleAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonRoleAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonRoleAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRoleAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonRoleAdd.IconMarginLeft = 11;
            this.bunifuButtonRoleAdd.IconPadding = 10;
            this.bunifuButtonRoleAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButtonRoleAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButtonRoleAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonRoleAdd.IconSize = 25;
            this.bunifuButtonRoleAdd.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleAdd.IdleBorderRadius = 24;
            this.bunifuButtonRoleAdd.IdleBorderThickness = 2;
            this.bunifuButtonRoleAdd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleAdd.IdleIconLeftImage = null;
            this.bunifuButtonRoleAdd.IdleIconRightImage = null;
            this.bunifuButtonRoleAdd.IndicateFocus = false;
            this.bunifuButtonRoleAdd.Location = new System.Drawing.Point(818, 596);
            this.bunifuButtonRoleAdd.Name = "bunifuButtonRoleAdd";
            this.bunifuButtonRoleAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButtonRoleAdd.OnDisabledState.BorderRadius = 24;
            this.bunifuButtonRoleAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleAdd.OnDisabledState.BorderThickness = 2;
            this.bunifuButtonRoleAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRoleAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRoleAdd.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonRoleAdd.OnDisabledState.IconRightImage = null;
            this.bunifuButtonRoleAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRoleAdd.onHoverState.BorderRadius = 24;
            this.bunifuButtonRoleAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleAdd.onHoverState.BorderThickness = 2;
            this.bunifuButtonRoleAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButtonRoleAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRoleAdd.onHoverState.IconLeftImage = null;
            this.bunifuButtonRoleAdd.onHoverState.IconRightImage = null;
            this.bunifuButtonRoleAdd.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRoleAdd.OnIdleState.BorderRadius = 24;
            this.bunifuButtonRoleAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButtonRoleAdd.OnIdleState.BorderThickness = 2;
            this.bunifuButtonRoleAdd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuButtonRoleAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifuButtonRoleAdd.OnIdleState.IconLeftImage = null;
            this.bunifuButtonRoleAdd.OnIdleState.IconRightImage = null;
            this.bunifuButtonRoleAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRoleAdd.OnPressedState.BorderRadius = 24;
            this.bunifuButtonRoleAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRoleAdd.OnPressedState.BorderThickness = 2;
            this.bunifuButtonRoleAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButtonRoleAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRoleAdd.OnPressedState.IconLeftImage = null;
            this.bunifuButtonRoleAdd.OnPressedState.IconRightImage = null;
            this.bunifuButtonRoleAdd.Size = new System.Drawing.Size(130, 50);
            this.bunifuButtonRoleAdd.TabIndex = 34;
            this.bunifuButtonRoleAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonRoleAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonRoleAdd.TextMarginLeft = 0;
            this.bunifuButtonRoleAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButtonRoleAdd, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButtonRoleAdd, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButtonRoleAdd, "");
            this.bunifuButtonRoleAdd.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonRoleAdd.Click += new System.EventHandler(this.bunifuButtonRoleAdd_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton2.ButtonText = "Danh sách các phân quyền trong hệ thống";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges4;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleBorderRadius = 60;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(94, 95);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 60;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 60;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.OnIdleState.BorderRadius = 60;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 60;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(341, 36);
            this.bunifuButton2.TabIndex = 27;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton2, "");
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton1.ButtonText = "Danh sách các chức năng";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges5;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleBorderRadius = 60;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(610, 95);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 60;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 60;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.BorderRadius = 60;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 60;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(273, 36);
            this.bunifuButton1.TabIndex = 26;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton1, "");
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton10
            // 
            this.bunifuButton10.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.bunifuButton10.AllowAnimations = true;
            this.bunifuButton10.AllowMouseEffects = true;
            this.bunifuButton10.AllowToggling = false;
            this.bunifuButton10.AnimationSpeed = 200;
            this.bunifuButton10.AutoGenerateColors = false;
            this.bunifuButton10.AutoRoundBorders = false;
            this.bunifuButton10.AutoSizeLeftIcon = true;
            this.bunifuButton10.AutoSizeRightIcon = true;
            this.bunifuButton10.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton10.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuButton10.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton10.BackgroundImage")));
            this.bunifuButton10.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton10.ButtonText = "";
            this.bunifuButton10.ButtonTextMarginLeft = 0;
            this.bunifuButton10.ColorContrastOnClick = 45;
            this.bunifuButton10.ColorContrastOnHover = 45;
            this.bunifuButton10.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton10.CustomizableEdges = borderEdges6;
            this.bunifuButton10.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton10.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton10.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton10.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton10.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton10.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton10.ForeColor = System.Drawing.Color.White;
            this.bunifuButton10.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton10.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton10.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton10.IconMarginLeft = 11;
            this.bunifuButton10.IconPadding = 10;
            this.bunifuButton10.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton10.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton10.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton10.IconSize = 25;
            this.bunifuButton10.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuButton10.IdleBorderRadius = 1;
            this.bunifuButton10.IdleBorderThickness = 1;
            this.bunifuButton10.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuButton10.IdleIconLeftImage = null;
            this.bunifuButton10.IdleIconRightImage = null;
            this.bunifuButton10.IndicateFocus = false;
            this.bunifuButton10.Location = new System.Drawing.Point(497, 137);
            this.bunifuButton10.Name = "bunifuButton10";
            this.bunifuButton10.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton10.OnDisabledState.BorderRadius = 1;
            this.bunifuButton10.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton10.OnDisabledState.BorderThickness = 1;
            this.bunifuButton10.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton10.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton10.OnDisabledState.IconLeftImage = null;
            this.bunifuButton10.OnDisabledState.IconRightImage = null;
            this.bunifuButton10.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton10.onHoverState.BorderRadius = 1;
            this.bunifuButton10.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton10.onHoverState.BorderThickness = 1;
            this.bunifuButton10.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton10.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton10.onHoverState.IconLeftImage = null;
            this.bunifuButton10.onHoverState.IconRightImage = null;
            this.bunifuButton10.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuButton10.OnIdleState.BorderRadius = 1;
            this.bunifuButton10.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton10.OnIdleState.BorderThickness = 1;
            this.bunifuButton10.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuButton10.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton10.OnIdleState.IconLeftImage = null;
            this.bunifuButton10.OnIdleState.IconRightImage = null;
            this.bunifuButton10.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton10.OnPressedState.BorderRadius = 1;
            this.bunifuButton10.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton10.OnPressedState.BorderThickness = 1;
            this.bunifuButton10.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton10.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton10.OnPressedState.IconLeftImage = null;
            this.bunifuButton10.OnPressedState.IconRightImage = null;
            this.bunifuButton10.Size = new System.Drawing.Size(3, 440);
            this.bunifuButton10.TabIndex = 24;
            this.bunifuButton10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton10.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton10.TextMarginLeft = 0;
            this.bunifuButton10.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.bunifuButton10, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton10, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton10, "");
            this.bunifuButton10.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuDataGridViewRoleDetail
            // 
            this.bunifuDataGridViewRoleDetail.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(223)))), ((int)(((byte)(223)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewRoleDetail.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridViewRoleDetail.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewRoleDetail.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuDataGridViewRoleDetail.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.bunifuDataGridViewRoleDetail.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewRoleDetail.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Teal;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewRoleDetail.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridViewRoleDetail.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(223)))), ((int)(((byte)(223)))));
            this.bunifuDataGridViewRoleDetail.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewRoleDetail.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.bunifuDataGridViewRoleDetail.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.BackColor = System.Drawing.Color.Teal;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(216)))), ((int)(((byte)(216)))));
            this.bunifuDataGridViewRoleDetail.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Teal;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewRoleDetail.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.bunifuDataGridViewRoleDetail.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.Name = null;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.bunifuDataGridViewRoleDetail.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewRoleDetail.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewRoleDetail.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.bunifuDataGridViewRoleDetail.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewRoleDetail.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridViewRoleDetail.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewRoleDetail.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(216)))), ((int)(((byte)(216)))));
            this.bunifuDataGridViewRoleDetail.HeaderBackColor = System.Drawing.Color.Teal;
            this.bunifuDataGridViewRoleDetail.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewRoleDetail.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRoleDetail.Location = new System.Drawing.Point(506, 137);
            this.bunifuDataGridViewRoleDetail.Name = "bunifuDataGridViewRoleDetail";
            this.bunifuDataGridViewRoleDetail.RowHeadersVisible = false;
            this.bunifuDataGridViewRoleDetail.RowHeadersWidth = 62;
            this.bunifuDataGridViewRoleDetail.RowTemplate.Height = 40;
            this.bunifuDataGridViewRoleDetail.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewRoleDetail.Size = new System.Drawing.Size(459, 440);
            this.bunifuDataGridViewRoleDetail.TabIndex = 4;
            this.bunifuDataGridViewRoleDetail.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Teal;
            this.bunifuToolTip1.SetToolTip(this.bunifuDataGridViewRoleDetail, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuDataGridViewRoleDetail, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuDataGridViewRoleDetail, "");
            // 
            // bunifuDataGridViewRole
            // 
            this.bunifuDataGridViewRole.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(223)))), ((int)(((byte)(223)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewRole.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridViewRole.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridViewRole.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuDataGridViewRole.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.bunifuDataGridViewRole.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridViewRole.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.Teal;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridViewRole.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.bunifuDataGridViewRole.ColumnHeadersHeight = 40;
            this.bunifuDataGridViewRole.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(223)))), ((int)(((byte)(223)))));
            this.bunifuDataGridViewRole.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewRole.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewRole.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.bunifuDataGridViewRole.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRole.CurrentTheme.BackColor = System.Drawing.Color.Teal;
            this.bunifuDataGridViewRole.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(216)))), ((int)(((byte)(216)))));
            this.bunifuDataGridViewRole.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Teal;
            this.bunifuDataGridViewRole.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewRole.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRole.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(102)))), ((int)(((byte)(102)))));
            this.bunifuDataGridViewRole.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRole.CurrentTheme.Name = null;
            this.bunifuDataGridViewRole.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            this.bunifuDataGridViewRole.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridViewRole.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridViewRole.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            this.bunifuDataGridViewRole.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(229)))), ((int)(((byte)(229)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(178)))), ((int)(((byte)(178)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridViewRole.DefaultCellStyle = dataGridViewCellStyle6;
            this.bunifuDataGridViewRole.EnableHeadersVisualStyles = false;
            this.bunifuDataGridViewRole.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(216)))), ((int)(((byte)(216)))));
            this.bunifuDataGridViewRole.HeaderBackColor = System.Drawing.Color.Teal;
            this.bunifuDataGridViewRole.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridViewRole.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridViewRole.Location = new System.Drawing.Point(32, 137);
            this.bunifuDataGridViewRole.Name = "bunifuDataGridViewRole";
            this.bunifuDataGridViewRole.RowHeadersVisible = false;
            this.bunifuDataGridViewRole.RowHeadersWidth = 62;
            this.bunifuDataGridViewRole.RowTemplate.Height = 40;
            this.bunifuDataGridViewRole.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridViewRole.Size = new System.Drawing.Size(459, 440);
            this.bunifuDataGridViewRole.TabIndex = 4;
            this.bunifuDataGridViewRole.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Teal;
            this.bunifuToolTip1.SetToolTip(this.bunifuDataGridViewRole, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuDataGridViewRole, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuDataGridViewRole, "");
            this.bunifuDataGridViewRole.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.bunifuDataGridViewRole_CellClick);
            // 
            // bunifubuttonRoleDeleteSearch
            // 
            this.bunifubuttonRoleDeleteSearch.ActiveBorderThickness = 1;
            this.bunifubuttonRoleDeleteSearch.ActiveCornerRadius = 20;
            this.bunifubuttonRoleDeleteSearch.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifubuttonRoleDeleteSearch.ActiveForecolor = System.Drawing.Color.White;
            this.bunifubuttonRoleDeleteSearch.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifubuttonRoleDeleteSearch.BackColor = System.Drawing.Color.Transparent;
            this.bunifubuttonRoleDeleteSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifubuttonRoleDeleteSearch.BackgroundImage")));
            this.bunifubuttonRoleDeleteSearch.ButtonText = "Xóa tìm kiếm";
            this.bunifubuttonRoleDeleteSearch.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifubuttonRoleDeleteSearch.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifubuttonRoleDeleteSearch.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifubuttonRoleDeleteSearch.IdleBorderThickness = 1;
            this.bunifubuttonRoleDeleteSearch.IdleCornerRadius = 60;
            this.bunifubuttonRoleDeleteSearch.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifubuttonRoleDeleteSearch.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifubuttonRoleDeleteSearch.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(7)))), ((int)(((byte)(58)))), ((int)(((byte)(82)))));
            this.bunifubuttonRoleDeleteSearch.Location = new System.Drawing.Point(736, 14);
            this.bunifubuttonRoleDeleteSearch.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifubuttonRoleDeleteSearch.Name = "bunifubuttonRoleDeleteSearch";
            this.bunifubuttonRoleDeleteSearch.Size = new System.Drawing.Size(128, 64);
            this.bunifubuttonRoleDeleteSearch.TabIndex = 3;
            this.bunifubuttonRoleDeleteSearch.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuToolTip1.SetToolTip(this.bunifubuttonRoleDeleteSearch, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifubuttonRoleDeleteSearch, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifubuttonRoleDeleteSearch, "");
            this.bunifubuttonRoleDeleteSearch.Click += new System.EventHandler(this.bunifubuttonRoleDeleteSearch_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cambria", 13F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(122, 39);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(83, 20);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Tìm kiếm :";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuTextBoxRoleSearch
            // 
            this.bunifuTextBoxRoleSearch.AcceptsReturn = false;
            this.bunifuTextBoxRoleSearch.AcceptsTab = false;
            this.bunifuTextBoxRoleSearch.AnimationSpeed = 200;
            this.bunifuTextBoxRoleSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxRoleSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxRoleSearch.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBoxRoleSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxRoleSearch.BackgroundImage")));
            this.bunifuTextBoxRoleSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxRoleSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxRoleSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxRoleSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxRoleSearch.BorderRadius = 1;
            this.bunifuTextBoxRoleSearch.BorderThickness = 1;
            this.bunifuTextBoxRoleSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxRoleSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxRoleSearch.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxRoleSearch.DefaultText = "";
            this.bunifuTextBoxRoleSearch.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuTextBoxRoleSearch.HideSelection = true;
            this.bunifuTextBoxRoleSearch.IconLeft = null;
            this.bunifuTextBoxRoleSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxRoleSearch.IconPadding = 10;
            this.bunifuTextBoxRoleSearch.IconRight = null;
            this.bunifuTextBoxRoleSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxRoleSearch.Lines = new string[0];
            this.bunifuTextBoxRoleSearch.Location = new System.Drawing.Point(211, 30);
            this.bunifuTextBoxRoleSearch.MaxLength = 32767;
            this.bunifuTextBoxRoleSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxRoleSearch.Modified = false;
            this.bunifuTextBoxRoleSearch.Multiline = false;
            this.bunifuTextBoxRoleSearch.Name = "bunifuTextBoxRoleSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxRoleSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxRoleSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxRoleSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxRoleSearch.OnIdleState = stateProperties4;
            this.bunifuTextBoxRoleSearch.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxRoleSearch.PasswordChar = '\0';
            this.bunifuTextBoxRoleSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxRoleSearch.PlaceholderText = "Enter text";
            this.bunifuTextBoxRoleSearch.ReadOnly = false;
            this.bunifuTextBoxRoleSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxRoleSearch.SelectedText = "";
            this.bunifuTextBoxRoleSearch.SelectionLength = 0;
            this.bunifuTextBoxRoleSearch.SelectionStart = 0;
            this.bunifuTextBoxRoleSearch.ShortcutsEnabled = true;
            this.bunifuTextBoxRoleSearch.Size = new System.Drawing.Size(518, 39);
            this.bunifuTextBoxRoleSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxRoleSearch.TabIndex = 1;
            this.bunifuTextBoxRoleSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxRoleSearch.TextMarginBottom = 0;
            this.bunifuTextBoxRoleSearch.TextMarginLeft = 3;
            this.bunifuTextBoxRoleSearch.TextMarginTop = 0;
            this.bunifuTextBoxRoleSearch.TextPlaceholder = "Enter text";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBoxRoleSearch, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBoxRoleSearch, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBoxRoleSearch, "");
            this.bunifuTextBoxRoleSearch.UseSystemPasswordChar = false;
            this.bunifuTextBoxRoleSearch.WordWrap = true;
            // 
            // FormMainRole
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Name = "FormMainRole";
            this.Size = new System.Drawing.Size(1095, 717);
            this.bunifuToolTip1.SetToolTip(this, "");
            this.bunifuToolTip1.SetToolTipIcon(this, null);
            this.bunifuToolTip1.SetToolTipTitle(this, "");
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewRoleDetail)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridViewRole)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
        private Bunifu.Framework.UI.BunifuThinButton2 bunifubuttonRoleDeleteSearch;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxRoleSearch;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewRole;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton10;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridViewRoleDetail;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonRoleDelete;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonRoleEdit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonRoleAdd;
    }
}
