//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL_MANAGEMENT_SOURCE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_generated_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_1_generated_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10130_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_10130_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _145411_OTQZ7A_227_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_145411_OTQZ7A_227_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _19767_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_19767_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2001_i105_001_isometric_surgeon_doctor_flowchart_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_2001_i105_001_isometric_surgeon_doctor_flowchart_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2318_R0lVIEFOTiAwNzAtMTA5_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_2318_R0lVIEFOTiAwNzAtMTA5_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25591_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_25591_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview__1_1 {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview__1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview__1_2 {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview__1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview__1_2___Copy {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview__1_2___Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview__1_2___Copy___Copy {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview__1_2___Copy___Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3varbuq4_removebg_preview__2_2___Copy {
            get {
                object obj = ResourceManager.GetObject("_3varbuq4_removebg_preview__2_2___Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40300_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_40300_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5245433_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_5245433_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5413809_effects_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_5413809_effects_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5l61_4oxe_180209_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_5l61_4oxe_180209_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5l61_4oxe_180209_removebg_preview___Copy {
            get {
                object obj = ResourceManager.GetObject("_5l61_4oxe_180209_removebg_preview___Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7071_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_7071_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7091_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_7091_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7317129_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_7317129_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _76b414fe4610989ff694005085de921a_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_76b414fe4610989ff694005085de921a_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _78pf2th5_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_78pf2th5_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81328514_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_81328514_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81328524_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_81328524_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _823_generated_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_823_generated_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Biomedical_Fresh_And_Simple_Medical_Technology_Poster_Background_Wallpaper_Image_For_Free_Download___Pngtree_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Biomedical_Fresh_And_Simple_Medical_Technology_Poster_Background_Wallpaper_Image_" +
                        "For_Free_Download___Pngtree_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Hospital_Medical_Western_Medicine_Poster_Background_Wallpaper_Image_For_Free_Download___Pngtree_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Blue_Hospital_Medical_Western_Medicine_Poster_Background_Wallpaper_Image_For_Free" +
                        "_Download___Pngtree_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Free__Medical__Health__Research_Background_Images__Medical_Health_Poster_Background_Photo_Background_PNG_and_Vectors_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Free__Medical__Health__Research_Background_Images__Medical_Health_Poster_Backgrou" +
                        "nd_Photo_Background_PNG_and_Vectors_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap handdrawn_vector_61_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("handdrawn_vector_61_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap handdrawn_vector_61_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("handdrawn_vector_61_removebg_preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap handdrawn_vector_61_removebg_preview2 {
            get {
                object obj = ResourceManager.GetObject("handdrawn_vector_61_removebg_preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i88i_lnik_180209_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("i88i_lnik_180209_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_closed_eye_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_closed_eye_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_eye_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_eye_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maximize {
            get {
                object obj = ResourceManager.GetObject("maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OL1V2Q0_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("OL1V2Q0_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_roundtable_png_image_5410543 {
            get {
                object obj = ResourceManager.GetObject("pngtree_roundtable_png_image_5410543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retro_error_message_illustration_in_pixel_style_vector_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("retro_error_message_illustration_in_pixel_style_vector_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2023_12_31_163312 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2023_12_31_163312", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2023_12_31_163445 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2023_12_31_163445", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2023_12_31_163600 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2023_12_31_163600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2023_12_31_163629 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2023_12_31_163629", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_01_02_185836 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024_01_02_185836", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_01_02_185836_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024_01_02_185836_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_01_02_185900 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024_01_02_185900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_2024_01_02_185900_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Screenshot_2024_01_02_185900_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tai_xuong__1__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("tai_xuong__1__removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tai_xuong__2__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("tai_xuong__2__removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Telegram_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Telegram_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_3d_rendered_icon_medical_hospital_illustraion_27252245 {
            get {
                object obj = ResourceManager.GetObject("vecteezy_3d_rendered_icon_medical_hospital_illustraion_27252245", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_a_medical_staff_group_of_doctors_and_nurses_standing_in_7382696_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("vecteezy_a_medical_staff_group_of_doctors_and_nurses_standing_in_7382696_removebg" +
                        "_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_a_patient_consults_a_doctor_and_nurse__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("vecteezy_a_patient_consults_a_doctor_and_nurse__removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_blood_test_vector_icon_18758827_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("vecteezy_blood_test_vector_icon_18758827_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_remove" +
                        "bg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_remove" +
                        "bg_preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_removebg_preview2 {
            get {
                object obj = ResourceManager.GetObject("vecteezy_cute_adorable_cartoon_stationery_yellow_pen_pencil_boy_15737572_1_remove" +
                        "bg_preview2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_flat_isometric_illustration_concept_symbol_of_the_best_7885579_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("vecteezy_flat_isometric_illustration_concept_symbol_of_the_best_7885579_removebg_" +
                        "preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_hospital_bed_in_circle_icon_intensive_care_unit_icon_4745587 {
            get {
                object obj = ResourceManager.GetObject("vecteezy_hospital_bed_in_circle_icon_intensive_care_unit_icon_4745587", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_hospital_bed_in_circle_icon_intensive_care_unit_icon_4745587_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("vecteezy_hospital_bed_in_circle_icon_intensive_care_unit_icon_4745587_removebg_pr" +
                        "eview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vecteezy_interface_plus_user_business_flat_line_filled_icon_vector_19177343_removebg_preview__1_ {
            get {
                object obj = ResourceManager.GetObject("vecteezy_interface_plus_user_business_flat_line_filled_icon_vector_19177343_remov" +
                        "ebg_preview__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z4953206934367_014bc3b5af9952b68f5b02289aaceeca {
            get {
                object obj = ResourceManager.GetObject("z4953206934367_014bc3b5af9952b68f5b02289aaceeca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("z5030631053744_2e9b4f844cb98aa60abede7ce3520931_removebg_preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap z5030867747912_8bf5b5c157107b7c880b4fc92925e287_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("z5030867747912_8bf5b5c157107b7c880b4fc92925e287_removebg_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
