
namespace HOSPITAL_MANAGEMENT_SOURCE.GUI
{
    partial class FormHFDetail
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormHFDetail));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.labelX5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxTreatment = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelAddress = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxPatientState = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonClose = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buttonOk = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dateCreate = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.labelX4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.labelX3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.labelX2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lableX1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textBoxPrehistory = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBoxPatientID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBoxHFID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textBoxDisease = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelHCID = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 50;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = null;
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = null;
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = null;
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = null;
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(221)))), ((int)(((byte)(85)))));
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI Semibold", 9F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.DimGray;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 50;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuShadowPanel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(153)))), ((int)(((byte)(139)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(153)))), ((int)(((byte)(139)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(110)))), ((int)(((byte)(129)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(647, 701);
            this.bunifuGradientPanel1.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuGradientPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuGradientPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuGradientPanel1, "");
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuShadowPanel1.BorderRadius = 20;
            this.bunifuShadowPanel1.BorderThickness = 2;
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuTextBox1);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuShadowPanel1.Controls.Add(this.labelX5);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxTreatment);
            this.bunifuShadowPanel1.Controls.Add(this.labelAddress);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxPatientState);
            this.bunifuShadowPanel1.Controls.Add(this.buttonClose);
            this.bunifuShadowPanel1.Controls.Add(this.buttonOk);
            this.bunifuShadowPanel1.Controls.Add(this.dateCreate);
            this.bunifuShadowPanel1.Controls.Add(this.labelX4);
            this.bunifuShadowPanel1.Controls.Add(this.labelX3);
            this.bunifuShadowPanel1.Controls.Add(this.labelX2);
            this.bunifuShadowPanel1.Controls.Add(this.lableX1);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxPrehistory);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxPatientID);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxHFID);
            this.bunifuShadowPanel1.Controls.Add(this.textBoxDisease);
            this.bunifuShadowPanel1.Controls.Add(this.labelHCID);
            this.bunifuShadowPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Gradient;
            this.bunifuShadowPanel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(26, 16);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(150)))), ((int)(((byte)(220)))), ((int)(((byte)(213)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(255)))), ((int)(((byte)(232)))));
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(602, 666);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuShadowPanel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuShadowPanel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuShadowPanel1, "");
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.bunifuPictureBox1.BorderRadius = 83;
            this.bunifuPictureBox1.Image = global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources._823_generated_removebg_preview;
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(429, -26);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(166, 166);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 28;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.bunifuPictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuPictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuPictureBox1, "");
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // labelX5
            // 
            this.labelX5.AllowParentOverrides = false;
            this.labelX5.AutoEllipsis = false;
            this.labelX5.CursorType = null;
            this.labelX5.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.labelX5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.labelX5.Location = new System.Drawing.Point(56, 524);
            this.labelX5.Name = "labelX5";
            this.labelX5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX5.Size = new System.Drawing.Size(111, 19);
            this.labelX5.TabIndex = 27;
            this.labelX5.Text = "Hướng điều trị";
            this.labelX5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelX5, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelX5, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelX5, "");
            // 
            // textBoxTreatment
            // 
            this.textBoxTreatment.AcceptsReturn = false;
            this.textBoxTreatment.AcceptsTab = false;
            this.textBoxTreatment.AnimationSpeed = 200;
            this.textBoxTreatment.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxTreatment.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxTreatment.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxTreatment.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxTreatment.BackgroundImage")));
            this.textBoxTreatment.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxTreatment.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxTreatment.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxTreatment.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxTreatment.BorderRadius = 10;
            this.textBoxTreatment.BorderThickness = 1;
            this.textBoxTreatment.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxTreatment.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxTreatment.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxTreatment.DefaultText = "";
            this.textBoxTreatment.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxTreatment.ForeColor = System.Drawing.Color.Black;
            this.textBoxTreatment.HideSelection = true;
            this.textBoxTreatment.IconLeft = null;
            this.textBoxTreatment.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxTreatment.IconPadding = 10;
            this.textBoxTreatment.IconRight = null;
            this.textBoxTreatment.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxTreatment.Lines = new string[0];
            this.textBoxTreatment.Location = new System.Drawing.Point(51, 547);
            this.textBoxTreatment.MaxLength = 32767;
            this.textBoxTreatment.MinimumSize = new System.Drawing.Size(2, 2);
            this.textBoxTreatment.Modified = false;
            this.textBoxTreatment.Multiline = false;
            this.textBoxTreatment.Name = "textBoxTreatment";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxTreatment.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxTreatment.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxTreatment.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxTreatment.OnIdleState = stateProperties8;
            this.textBoxTreatment.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxTreatment.PasswordChar = '\0';
            this.textBoxTreatment.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxTreatment.PlaceholderText = "Nhập hướng điều trị";
            this.textBoxTreatment.ReadOnly = false;
            this.textBoxTreatment.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxTreatment.SelectedText = "";
            this.textBoxTreatment.SelectionLength = 0;
            this.textBoxTreatment.SelectionStart = 0;
            this.textBoxTreatment.ShortcutsEnabled = true;
            this.textBoxTreatment.Size = new System.Drawing.Size(425, 36);
            this.textBoxTreatment.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxTreatment.TabIndex = 26;
            this.textBoxTreatment.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxTreatment.TextMarginBottom = 0;
            this.textBoxTreatment.TextMarginLeft = 3;
            this.textBoxTreatment.TextMarginTop = 0;
            this.textBoxTreatment.TextPlaceholder = "Nhập hướng điều trị";
            this.bunifuToolTip1.SetToolTip(this.textBoxTreatment, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxTreatment, global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxTreatment, "Warning");
            this.textBoxTreatment.UseSystemPasswordChar = false;
            this.textBoxTreatment.WordWrap = true;
            // 
            // labelAddress
            // 
            this.labelAddress.AllowParentOverrides = false;
            this.labelAddress.AutoEllipsis = false;
            this.labelAddress.CursorType = null;
            this.labelAddress.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.labelAddress.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.labelAddress.Location = new System.Drawing.Point(56, 322);
            this.labelAddress.Name = "labelAddress";
            this.labelAddress.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelAddress.Size = new System.Drawing.Size(163, 19);
            this.labelAddress.TabIndex = 25;
            this.labelAddress.Text = "Tình trạng bệnh nhân";
            this.labelAddress.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelAddress.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelAddress, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelAddress, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelAddress, "");
            // 
            // textBoxPatientState
            // 
            this.textBoxPatientState.AcceptsReturn = false;
            this.textBoxPatientState.AcceptsTab = false;
            this.textBoxPatientState.AnimationSpeed = 200;
            this.textBoxPatientState.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxPatientState.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxPatientState.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxPatientState.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxPatientState.BackgroundImage")));
            this.textBoxPatientState.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxPatientState.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxPatientState.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxPatientState.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxPatientState.BorderRadius = 10;
            this.textBoxPatientState.BorderThickness = 1;
            this.textBoxPatientState.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxPatientState.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientState.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxPatientState.DefaultText = "";
            this.textBoxPatientState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxPatientState.ForeColor = System.Drawing.Color.Black;
            this.textBoxPatientState.HideSelection = true;
            this.textBoxPatientState.IconLeft = null;
            this.textBoxPatientState.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientState.IconPadding = 10;
            this.textBoxPatientState.IconRight = null;
            this.textBoxPatientState.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientState.Lines = new string[0];
            this.textBoxPatientState.Location = new System.Drawing.Point(51, 345);
            this.textBoxPatientState.MaxLength = 32767;
            this.textBoxPatientState.MinimumSize = new System.Drawing.Size(2, 2);
            this.textBoxPatientState.Modified = false;
            this.textBoxPatientState.Multiline = false;
            this.textBoxPatientState.Name = "textBoxPatientState";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientState.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxPatientState.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientState.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientState.OnIdleState = stateProperties12;
            this.textBoxPatientState.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxPatientState.PasswordChar = '\0';
            this.textBoxPatientState.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxPatientState.PlaceholderText = "Nhập tình trạng";
            this.textBoxPatientState.ReadOnly = false;
            this.textBoxPatientState.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxPatientState.SelectedText = "";
            this.textBoxPatientState.SelectionLength = 0;
            this.textBoxPatientState.SelectionStart = 0;
            this.textBoxPatientState.ShortcutsEnabled = true;
            this.textBoxPatientState.Size = new System.Drawing.Size(425, 36);
            this.textBoxPatientState.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxPatientState.TabIndex = 24;
            this.textBoxPatientState.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxPatientState.TextMarginBottom = 0;
            this.textBoxPatientState.TextMarginLeft = 3;
            this.textBoxPatientState.TextMarginTop = 0;
            this.textBoxPatientState.TextPlaceholder = "Nhập tình trạng";
            this.bunifuToolTip1.SetToolTip(this.textBoxPatientState, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxPatientState, global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxPatientState, "Warning");
            this.textBoxPatientState.UseSystemPasswordChar = false;
            this.textBoxPatientState.WordWrap = true;
            // 
            // buttonClose
            // 
            this.buttonClose.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonClose.AllowAnimations = true;
            this.buttonClose.AllowMouseEffects = true;
            this.buttonClose.AllowToggling = false;
            this.buttonClose.AnimationSpeed = 200;
            this.buttonClose.AutoGenerateColors = false;
            this.buttonClose.AutoRoundBorders = false;
            this.buttonClose.AutoSizeLeftIcon = true;
            this.buttonClose.AutoSizeRightIcon = true;
            this.buttonClose.BackColor = System.Drawing.Color.Transparent;
            this.buttonClose.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(236)))), ((int)(((byte)(250)))));
            this.buttonClose.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonClose.BackgroundImage")));
            this.buttonClose.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.ButtonText = "Thoát";
            this.buttonClose.ButtonTextMarginLeft = 0;
            this.buttonClose.ColorContrastOnClick = 45;
            this.buttonClose.ColorContrastOnHover = 45;
            this.buttonClose.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonClose.CustomizableEdges = borderEdges1;
            this.buttonClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonClose.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonClose.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonClose.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.buttonClose.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonClose.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonClose.IconMarginLeft = 11;
            this.buttonClose.IconPadding = 10;
            this.buttonClose.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonClose.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonClose.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonClose.IconSize = 25;
            this.buttonClose.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.IdleBorderRadius = 40;
            this.buttonClose.IdleBorderThickness = 1;
            this.buttonClose.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(236)))), ((int)(((byte)(250)))));
            this.buttonClose.IdleIconLeftImage = null;
            this.buttonClose.IdleIconRightImage = null;
            this.buttonClose.IndicateFocus = false;
            this.buttonClose.Location = new System.Drawing.Point(431, 600);
            this.buttonClose.Name = "buttonClose";
            this.buttonClose.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonClose.OnDisabledState.BorderRadius = 40;
            this.buttonClose.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnDisabledState.BorderThickness = 1;
            this.buttonClose.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonClose.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonClose.OnDisabledState.IconLeftImage = null;
            this.buttonClose.OnDisabledState.IconRightImage = null;
            this.buttonClose.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonClose.onHoverState.BorderRadius = 40;
            this.buttonClose.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.onHoverState.BorderThickness = 1;
            this.buttonClose.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonClose.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonClose.onHoverState.IconLeftImage = null;
            this.buttonClose.onHoverState.IconRightImage = null;
            this.buttonClose.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonClose.OnIdleState.BorderRadius = 40;
            this.buttonClose.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnIdleState.BorderThickness = 1;
            this.buttonClose.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(236)))), ((int)(((byte)(250)))));
            this.buttonClose.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.buttonClose.OnIdleState.IconLeftImage = null;
            this.buttonClose.OnIdleState.IconRightImage = null;
            this.buttonClose.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.BorderRadius = 40;
            this.buttonClose.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonClose.OnPressedState.BorderThickness = 1;
            this.buttonClose.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonClose.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonClose.OnPressedState.IconLeftImage = null;
            this.buttonClose.OnPressedState.IconRightImage = null;
            this.buttonClose.Size = new System.Drawing.Size(106, 44);
            this.buttonClose.TabIndex = 23;
            this.buttonClose.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonClose.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonClose.TextMarginLeft = 0;
            this.buttonClose.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.buttonClose, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonClose, null);
            this.bunifuToolTip1.SetToolTipTitle(this.buttonClose, "");
            this.buttonClose.UseDefaultRadiusAndThickness = true;
            this.buttonClose.Click += new System.EventHandler(this.buttonClose_Click);
            // 
            // buttonOk
            // 
            this.buttonOk.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.buttonOk.AllowAnimations = true;
            this.buttonOk.AllowMouseEffects = true;
            this.buttonOk.AllowToggling = false;
            this.buttonOk.AnimationSpeed = 200;
            this.buttonOk.AutoGenerateColors = false;
            this.buttonOk.AutoRoundBorders = false;
            this.buttonOk.AutoSizeLeftIcon = true;
            this.buttonOk.AutoSizeRightIcon = true;
            this.buttonOk.BackColor = System.Drawing.Color.Transparent;
            this.buttonOk.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(236)))), ((int)(((byte)(250)))));
            this.buttonOk.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonOk.BackgroundImage")));
            this.buttonOk.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.ButtonText = "Đồng ý";
            this.buttonOk.ButtonTextMarginLeft = 0;
            this.buttonOk.ColorContrastOnClick = 45;
            this.buttonOk.ColorContrastOnHover = 45;
            this.buttonOk.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.buttonOk.CustomizableEdges = borderEdges2;
            this.buttonOk.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonOk.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonOk.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.buttonOk.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.buttonOk.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonOk.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonOk.IconMarginLeft = 11;
            this.buttonOk.IconPadding = 10;
            this.buttonOk.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonOk.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.buttonOk.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonOk.IconSize = 25;
            this.buttonOk.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.IdleBorderRadius = 40;
            this.buttonOk.IdleBorderThickness = 1;
            this.buttonOk.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(236)))), ((int)(((byte)(250)))));
            this.buttonOk.IdleIconLeftImage = null;
            this.buttonOk.IdleIconRightImage = null;
            this.buttonOk.IndicateFocus = false;
            this.buttonOk.Location = new System.Drawing.Point(293, 600);
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonOk.OnDisabledState.BorderRadius = 40;
            this.buttonOk.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnDisabledState.BorderThickness = 1;
            this.buttonOk.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonOk.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonOk.OnDisabledState.IconLeftImage = null;
            this.buttonOk.OnDisabledState.IconRightImage = null;
            this.buttonOk.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buttonOk.onHoverState.BorderRadius = 40;
            this.buttonOk.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.onHoverState.BorderThickness = 1;
            this.buttonOk.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(217)))), ((int)(((byte)(183)))));
            this.buttonOk.onHoverState.ForeColor = System.Drawing.Color.DimGray;
            this.buttonOk.onHoverState.IconLeftImage = null;
            this.buttonOk.onHoverState.IconRightImage = null;
            this.buttonOk.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(119)))), ((int)(((byte)(102)))));
            this.buttonOk.OnIdleState.BorderRadius = 40;
            this.buttonOk.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnIdleState.BorderThickness = 1;
            this.buttonOk.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(196)))), ((int)(((byte)(236)))), ((int)(((byte)(250)))));
            this.buttonOk.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.buttonOk.OnIdleState.IconLeftImage = null;
            this.buttonOk.OnIdleState.IconRightImage = null;
            this.buttonOk.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.BorderRadius = 40;
            this.buttonOk.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonOk.OnPressedState.BorderThickness = 1;
            this.buttonOk.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.buttonOk.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.buttonOk.OnPressedState.IconLeftImage = null;
            this.buttonOk.OnPressedState.IconRightImage = null;
            this.buttonOk.Size = new System.Drawing.Size(105, 44);
            this.buttonOk.TabIndex = 22;
            this.buttonOk.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonOk.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonOk.TextMarginLeft = 0;
            this.buttonOk.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuToolTip1.SetToolTip(this.buttonOk, "");
            this.bunifuToolTip1.SetToolTipIcon(this.buttonOk, null);
            this.bunifuToolTip1.SetToolTipTitle(this.buttonOk, "");
            this.buttonOk.UseDefaultRadiusAndThickness = true;
            // 
            // dateCreate
            // 
            this.dateCreate.AllowDrop = true;
            this.dateCreate.BackColor = System.Drawing.Color.Transparent;
            this.dateCreate.BorderRadius = 5;
            this.dateCreate.Color = System.Drawing.Color.Gainsboro;
            this.dateCreate.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dateCreate.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateCreate.DisabledColor = System.Drawing.Color.Gray;
            this.dateCreate.DisplayWeekNumbers = false;
            this.dateCreate.DPHeight = 0;
            this.dateCreate.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dateCreate.FillDatePicker = false;
            this.dateCreate.Font = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.dateCreate.ForeColor = System.Drawing.Color.Black;
            this.dateCreate.Icon = ((System.Drawing.Image)(resources.GetObject("dateCreate.Icon")));
            this.dateCreate.IconColor = System.Drawing.Color.DimGray;
            this.dateCreate.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateCreate.LeftTextMargin = 5;
            this.dateCreate.Location = new System.Drawing.Point(51, 281);
            this.dateCreate.MinimumSize = new System.Drawing.Size(4, 32);
            this.dateCreate.Name = "dateCreate";
            this.dateCreate.Size = new System.Drawing.Size(426, 32);
            this.dateCreate.TabIndex = 21;
            this.bunifuToolTip1.SetToolTip(this.dateCreate, "");
            this.bunifuToolTip1.SetToolTipIcon(this.dateCreate, null);
            this.bunifuToolTip1.SetToolTipTitle(this.dateCreate, "");
            this.dateCreate.Value = new System.DateTime(2023, 12, 8, 4, 30, 0, 0);
            // 
            // labelX4
            // 
            this.labelX4.AllowParentOverrides = false;
            this.labelX4.AutoEllipsis = false;
            this.labelX4.CursorType = null;
            this.labelX4.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.labelX4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.labelX4.Location = new System.Drawing.Point(56, 457);
            this.labelX4.Name = "labelX4";
            this.labelX4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX4.Size = new System.Drawing.Size(111, 19);
            this.labelX4.TabIndex = 20;
            this.labelX4.Text = "Bệnh mắc phải";
            this.labelX4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelX4, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelX4, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelX4, "");
            // 
            // labelX3
            // 
            this.labelX3.AllowParentOverrides = false;
            this.labelX3.AutoEllipsis = false;
            this.labelX3.CursorType = null;
            this.labelX3.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.labelX3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.labelX3.Location = new System.Drawing.Point(56, 390);
            this.labelX3.Name = "labelX3";
            this.labelX3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX3.Size = new System.Drawing.Size(113, 19);
            this.labelX3.TabIndex = 19;
            this.labelX3.Text = "Tiền sử bệnh lý";
            this.labelX3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelX3, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelX3, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelX3, "");
            // 
            // labelX2
            // 
            this.labelX2.AllowParentOverrides = false;
            this.labelX2.AutoEllipsis = false;
            this.labelX2.CursorType = null;
            this.labelX2.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.labelX2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.labelX2.Location = new System.Drawing.Point(56, 257);
            this.labelX2.Name = "labelX2";
            this.labelX2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelX2.Size = new System.Drawing.Size(64, 19);
            this.labelX2.TabIndex = 18;
            this.labelX2.Text = "Ngày lập";
            this.labelX2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelX2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelX2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelX2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelX2, "");
            // 
            // lableX1
            // 
            this.lableX1.AllowParentOverrides = false;
            this.lableX1.AutoEllipsis = false;
            this.lableX1.CursorType = null;
            this.lableX1.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.lableX1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.lableX1.Location = new System.Drawing.Point(56, 125);
            this.lableX1.Name = "lableX1";
            this.lableX1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lableX1.Size = new System.Drawing.Size(107, 19);
            this.lableX1.TabIndex = 17;
            this.lableX1.Text = "Mã bệnh nhân";
            this.lableX1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lableX1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.lableX1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.lableX1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.lableX1, "");
            // 
            // textBoxPrehistory
            // 
            this.textBoxPrehistory.AcceptsReturn = false;
            this.textBoxPrehistory.AcceptsTab = false;
            this.textBoxPrehistory.AnimationSpeed = 200;
            this.textBoxPrehistory.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxPrehistory.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxPrehistory.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxPrehistory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxPrehistory.BackgroundImage")));
            this.textBoxPrehistory.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxPrehistory.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxPrehistory.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxPrehistory.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxPrehistory.BorderRadius = 10;
            this.textBoxPrehistory.BorderThickness = 1;
            this.textBoxPrehistory.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxPrehistory.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPrehistory.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxPrehistory.DefaultText = "";
            this.textBoxPrehistory.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxPrehistory.ForeColor = System.Drawing.Color.Black;
            this.textBoxPrehistory.HideSelection = true;
            this.textBoxPrehistory.IconLeft = null;
            this.textBoxPrehistory.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPrehistory.IconPadding = 10;
            this.textBoxPrehistory.IconRight = null;
            this.textBoxPrehistory.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPrehistory.Lines = new string[0];
            this.textBoxPrehistory.Location = new System.Drawing.Point(51, 413);
            this.textBoxPrehistory.MaxLength = 32767;
            this.textBoxPrehistory.MinimumSize = new System.Drawing.Size(2, 2);
            this.textBoxPrehistory.Modified = false;
            this.textBoxPrehistory.Multiline = false;
            this.textBoxPrehistory.Name = "textBoxPrehistory";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPrehistory.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxPrehistory.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPrehistory.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPrehistory.OnIdleState = stateProperties16;
            this.textBoxPrehistory.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxPrehistory.PasswordChar = '\0';
            this.textBoxPrehistory.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxPrehistory.PlaceholderText = "Nhập tiền sử bệnh";
            this.textBoxPrehistory.ReadOnly = false;
            this.textBoxPrehistory.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxPrehistory.SelectedText = "";
            this.textBoxPrehistory.SelectionLength = 0;
            this.textBoxPrehistory.SelectionStart = 0;
            this.textBoxPrehistory.ShortcutsEnabled = true;
            this.textBoxPrehistory.Size = new System.Drawing.Size(425, 36);
            this.textBoxPrehistory.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxPrehistory.TabIndex = 15;
            this.textBoxPrehistory.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxPrehistory.TextMarginBottom = 0;
            this.textBoxPrehistory.TextMarginLeft = 3;
            this.textBoxPrehistory.TextMarginTop = 0;
            this.textBoxPrehistory.TextPlaceholder = "Nhập tiền sử bệnh";
            this.bunifuToolTip1.SetToolTip(this.textBoxPrehistory, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxPrehistory, global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxPrehistory, "Warning");
            this.textBoxPrehistory.UseSystemPasswordChar = false;
            this.textBoxPrehistory.WordWrap = true;
            // 
            // textBoxPatientID
            // 
            this.textBoxPatientID.AcceptsReturn = false;
            this.textBoxPatientID.AcceptsTab = false;
            this.textBoxPatientID.AnimationSpeed = 200;
            this.textBoxPatientID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxPatientID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxPatientID.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxPatientID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxPatientID.BackgroundImage")));
            this.textBoxPatientID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxPatientID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxPatientID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxPatientID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxPatientID.BorderRadius = 10;
            this.textBoxPatientID.BorderThickness = 1;
            this.textBoxPatientID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxPatientID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxPatientID.DefaultText = "";
            this.textBoxPatientID.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxPatientID.ForeColor = System.Drawing.Color.Black;
            this.textBoxPatientID.HideSelection = true;
            this.textBoxPatientID.IconLeft = null;
            this.textBoxPatientID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientID.IconPadding = 10;
            this.textBoxPatientID.IconRight = null;
            this.textBoxPatientID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxPatientID.Lines = new string[0];
            this.textBoxPatientID.Location = new System.Drawing.Point(51, 148);
            this.textBoxPatientID.MaxLength = 32767;
            this.textBoxPatientID.MinimumSize = new System.Drawing.Size(2, 2);
            this.textBoxPatientID.Modified = false;
            this.textBoxPatientID.Multiline = false;
            this.textBoxPatientID.Name = "textBoxPatientID";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientID.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxPatientID.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientID.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxPatientID.OnIdleState = stateProperties20;
            this.textBoxPatientID.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxPatientID.PasswordChar = '\0';
            this.textBoxPatientID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxPatientID.PlaceholderText = "Nhập mã bệnh nhân";
            this.textBoxPatientID.ReadOnly = true;
            this.textBoxPatientID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxPatientID.SelectedText = "";
            this.textBoxPatientID.SelectionLength = 0;
            this.textBoxPatientID.SelectionStart = 0;
            this.textBoxPatientID.ShortcutsEnabled = true;
            this.textBoxPatientID.Size = new System.Drawing.Size(425, 36);
            this.textBoxPatientID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxPatientID.TabIndex = 14;
            this.textBoxPatientID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxPatientID.TextMarginBottom = 0;
            this.textBoxPatientID.TextMarginLeft = 3;
            this.textBoxPatientID.TextMarginTop = 0;
            this.textBoxPatientID.TextPlaceholder = "Nhập mã bệnh nhân";
            this.bunifuToolTip1.SetToolTip(this.textBoxPatientID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxPatientID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxPatientID, "");
            this.textBoxPatientID.UseSystemPasswordChar = false;
            this.textBoxPatientID.WordWrap = true;
            // 
            // textBoxHFID
            // 
            this.textBoxHFID.AcceptsReturn = false;
            this.textBoxHFID.AcceptsTab = false;
            this.textBoxHFID.AnimationSpeed = 200;
            this.textBoxHFID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxHFID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxHFID.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxHFID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxHFID.BackgroundImage")));
            this.textBoxHFID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxHFID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxHFID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxHFID.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxHFID.BorderRadius = 20;
            this.textBoxHFID.BorderThickness = 1;
            this.textBoxHFID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxHFID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxHFID.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxHFID.DefaultText = "";
            this.textBoxHFID.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxHFID.ForeColor = System.Drawing.Color.Black;
            this.textBoxHFID.HideSelection = true;
            this.textBoxHFID.IconLeft = null;
            this.textBoxHFID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxHFID.IconPadding = 10;
            this.textBoxHFID.IconRight = null;
            this.textBoxHFID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxHFID.Lines = new string[0];
            this.textBoxHFID.Location = new System.Drawing.Point(51, 82);
            this.textBoxHFID.MaxLength = 32767;
            this.textBoxHFID.MinimumSize = new System.Drawing.Size(2, 2);
            this.textBoxHFID.Modified = false;
            this.textBoxHFID.Multiline = false;
            this.textBoxHFID.Name = "textBoxHFID";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxHFID.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxHFID.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxHFID.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxHFID.OnIdleState = stateProperties24;
            this.textBoxHFID.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxHFID.PasswordChar = '\0';
            this.textBoxHFID.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxHFID.PlaceholderText = "Nhập mã bệnh án";
            this.textBoxHFID.ReadOnly = true;
            this.textBoxHFID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxHFID.SelectedText = "";
            this.textBoxHFID.SelectionLength = 0;
            this.textBoxHFID.SelectionStart = 0;
            this.textBoxHFID.ShortcutsEnabled = true;
            this.textBoxHFID.Size = new System.Drawing.Size(425, 36);
            this.textBoxHFID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxHFID.TabIndex = 12;
            this.textBoxHFID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxHFID.TextMarginBottom = 0;
            this.textBoxHFID.TextMarginLeft = 3;
            this.textBoxHFID.TextMarginTop = 0;
            this.textBoxHFID.TextPlaceholder = "Nhập mã bệnh án";
            this.bunifuToolTip1.SetToolTip(this.textBoxHFID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxHFID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxHFID, "");
            this.textBoxHFID.UseSystemPasswordChar = false;
            this.textBoxHFID.WordWrap = true;
            // 
            // textBoxDisease
            // 
            this.textBoxDisease.AcceptsReturn = false;
            this.textBoxDisease.AcceptsTab = false;
            this.textBoxDisease.AnimationSpeed = 200;
            this.textBoxDisease.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textBoxDisease.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textBoxDisease.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxDisease.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textBoxDisease.BackgroundImage")));
            this.textBoxDisease.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.textBoxDisease.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textBoxDisease.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.textBoxDisease.BorderColorIdle = System.Drawing.Color.Silver;
            this.textBoxDisease.BorderRadius = 10;
            this.textBoxDisease.BorderThickness = 1;
            this.textBoxDisease.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textBoxDisease.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxDisease.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.textBoxDisease.DefaultText = "";
            this.textBoxDisease.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.textBoxDisease.ForeColor = System.Drawing.Color.Black;
            this.textBoxDisease.HideSelection = true;
            this.textBoxDisease.IconLeft = null;
            this.textBoxDisease.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxDisease.IconPadding = 10;
            this.textBoxDisease.IconRight = null;
            this.textBoxDisease.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textBoxDisease.Lines = new string[0];
            this.textBoxDisease.Location = new System.Drawing.Point(51, 480);
            this.textBoxDisease.MaxLength = 32767;
            this.textBoxDisease.MinimumSize = new System.Drawing.Size(2, 2);
            this.textBoxDisease.Modified = false;
            this.textBoxDisease.Multiline = false;
            this.textBoxDisease.Name = "textBoxDisease";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxDisease.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textBoxDisease.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxDisease.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties28.ForeColor = System.Drawing.Color.Black;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textBoxDisease.OnIdleState = stateProperties28;
            this.textBoxDisease.Padding = new System.Windows.Forms.Padding(3);
            this.textBoxDisease.PasswordChar = '\0';
            this.textBoxDisease.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.textBoxDisease.PlaceholderText = "Nhập bệnh mắc phải";
            this.textBoxDisease.ReadOnly = false;
            this.textBoxDisease.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textBoxDisease.SelectedText = "";
            this.textBoxDisease.SelectionLength = 0;
            this.textBoxDisease.SelectionStart = 0;
            this.textBoxDisease.ShortcutsEnabled = true;
            this.textBoxDisease.Size = new System.Drawing.Size(425, 36);
            this.textBoxDisease.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.textBoxDisease.TabIndex = 11;
            this.textBoxDisease.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textBoxDisease.TextMarginBottom = 0;
            this.textBoxDisease.TextMarginLeft = 3;
            this.textBoxDisease.TextMarginTop = 0;
            this.textBoxDisease.TextPlaceholder = "Nhập bệnh mắc phải";
            this.bunifuToolTip1.SetToolTip(this.textBoxDisease, "Không chứa số và ký tự đặc biệt");
            this.bunifuToolTip1.SetToolTipIcon(this.textBoxDisease, global::HOSPITAL_MANAGEMENT_SOURCE.Properties.Resources.retro_error_message_illustration_in_pixel_style_vector_removebg_preview);
            this.bunifuToolTip1.SetToolTipTitle(this.textBoxDisease, "Warning");
            this.textBoxDisease.UseSystemPasswordChar = false;
            this.textBoxDisease.WordWrap = true;
            // 
            // labelHCID
            // 
            this.labelHCID.AllowParentOverrides = false;
            this.labelHCID.AutoEllipsis = false;
            this.labelHCID.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelHCID.CursorType = System.Windows.Forms.Cursors.Default;
            this.labelHCID.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.labelHCID.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.labelHCID.Location = new System.Drawing.Point(56, 59);
            this.labelHCID.Name = "labelHCID";
            this.labelHCID.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.labelHCID.Size = new System.Drawing.Size(87, 19);
            this.labelHCID.TabIndex = 2;
            this.labelHCID.Text = "Mã bệnh án";
            this.labelHCID.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.labelHCID.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.labelHCID, "");
            this.bunifuToolTip1.SetToolTipIcon(this.labelHCID, null);
            this.bunifuToolTip1.SetToolTipTitle(this.labelHCID, "");
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Cambria", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(202, 28);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(100, 28);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "BỆNH ÁN";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Cambria", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(42)))), ((int)(((byte)(70)))), ((int)(((byte)(113)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(56, 192);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(112, 19);
            this.bunifuLabel2.TabIndex = 30;
            this.bunifuLabel2.Text = "Tên bệnh nhân";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuToolTip1.SetToolTip(this.bunifuLabel2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuLabel2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuLabel2, "");
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 10;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Cambria", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            this.bunifuTextBox1.ForeColor = System.Drawing.Color.Black;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(51, 215);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(2, 2);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(237)))), ((int)(((byte)(252)))), ((int)(((byte)(245)))));
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties4;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Gray;
            this.bunifuTextBox1.PlaceholderText = "Nhập tên bệnh nhân";
            this.bunifuTextBox1.ReadOnly = true;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(425, 36);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBox1.TabIndex = 29;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "Nhập tên bệnh nhân";
            this.bunifuToolTip1.SetToolTip(this.bunifuTextBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuTextBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuTextBox1, "");
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // FormHFDetail
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(647, 701);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "FormHFDetail";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormHFDetail";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel labelHCID;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxDisease;
        private Bunifu.UI.WinForms.BunifuLabel labelX4;
        private Bunifu.UI.WinForms.BunifuLabel labelX3;
        private Bunifu.UI.WinForms.BunifuLabel labelX2;
        private Bunifu.UI.WinForms.BunifuLabel lableX1;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxPrehistory;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxPatientID;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxHFID;
        private Bunifu.UI.WinForms.BunifuDatePicker dateCreate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonOk;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonClose;
        private Bunifu.UI.WinForms.BunifuLabel labelAddress;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxPatientState;
        private Bunifu.UI.WinForms.BunifuLabel labelX5;
        private Bunifu.UI.WinForms.BunifuTextBox textBoxTreatment;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
    }
}